In [1]:
a = [4,5,6,7]

In [2]:
print(a[2])

6


In [3]:
import numpy as np

In [4]:
two_dim = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
print(two_dim[0])

[1 2 3]


In [6]:
print(two_dim[1][2]) # For multi dimensional, we have to use [][] for each dimension to access the elements.

6


In [7]:
three_dim = np.array(([[[1,2,3],[4,5,6]], [[8,9,10], [11,23,45]]]))

In [8]:
print(three_dim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8  9 10]
  [11 23 45]]]


In [10]:
print(three_dim.ndim)

3


In [11]:
print(three_dim.shape)

(2, 2, 3)


In [12]:
print(three_dim[0][1])

[4 5 6]
