In [3]:
import numpy as np

In [15]:
a1 = np.array([[1,2],[4,5]])
print(a1.shape)

(2, 2)


In [17]:
a2 = np.array([[45,89], [90,56]])
print(a2.shape)

(2, 2)


In [8]:
vert_stack = np.vstack((a1,a2)) # stacks vertically

In [18]:
print(vert_stack, vert_stack.shape)

[[ 1  2]
 [ 4  5]
 [45 89]
 [90 56]] (4, 2)


In [11]:
horizontal_stack = np.hstack((a1,a2))

In [13]:
print(horizontal_stack, horizontal_stack.shape)

[[ 1  2 45 89]
 [ 4  5 90 56]] (2, 4)


In [23]:
hsplit = np.hsplit(a1, 2) # split into smaller arrays, here into 2 array

In [24]:
print(hsplit) 

[array([[1],
       [4]]), array([[2],
       [5]])]
