In [17]:
import numpy as np

In [18]:
import test

In [7]:
# 2x_1-x_2+x_3+x_4=6, equation 1,  x_1+2x_2-x_3-x_4=3, equation 2, -x_1+2x_2+2x_3+2x_4=14, equation 3, x_1-x_2+2x_3+x_4=8
# you will construct matrix 
# where each row represents one equation in the system and each column represents a variable 
# The free coefficients from the right sides of the equations you will put into vector 

In [20]:
a = np.array([[2,-1,1,1],[1,2,-1,-1], [-1,2,2,2],[1,-1,2,1]], dtype=np.dtype(float))
b = np.array([6,3,14,8], dtype=np.dtype(float))
test.test_matrix(a,b)

 All tests passed


In [29]:
# find determinant and solution for equation 1 
determinant_a = np.linalg.det(a)
print(determinant_a)
solution_a =np.linalg.solve(a,b)
print(solution_a)

-16.999999999999993
[2. 3. 4. 1.]


In [36]:
def MultiplyRow(M, row_num, row_num_multiple):
    # .copy() function is required here to keep the original matrix without any changes
    M_new = M.copy()     
    # exchange row_num of the matrix M_new with its multiple by row_num_multiple
    # Note: for simplicity, you can drop check if  row_num_multiple has non-zero value, which makes the operation valid
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new
def AddRows(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()     
    # multiply row_num_1 by row_num_1_multiple and add it to the row_num_2, 
    # exchanging row_num_2 of the matrix M_new with the result
    M_new[row_num_2] += M_new[row_num_1] * row_num_1_multiple
    return M_new

def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()     
    # exchange row_num_1 and row_num_2 of the matrix M_new
    M_new[row_num_1] = M_new[row_num_1] + M_new[row_num_2]
    M_new[row_num_2] = M_new[row_num_1] - M_new[row_num_2]
    M_new[row_num_1]
    return M_new
    

In [37]:
A_test = np.array([
        [1, -2, 3, -4],
        [-5, 6, -7, 8],
        [-4, 3, -2, 1], 
        [8, -7, 6, -5]
    ], dtype=np.dtype(float))
print("Original matrix:")
print(A_test)

print("\nOriginal matrix after its third row is multiplied by -2:")
print(MultiplyRow(A_test,2,-2))

print("\nOriginal matrix after exchange of the third row with the sum of itself and first row multiplied by 4:")
print(AddRows(A_test,0,2,4))

print("\nOriginal matrix after exchange of its first and third rows:")
print(SwapRows(A_test,0,2))

Original matrix:
[[ 1. -2.  3. -4.]
 [-5.  6. -7.  8.]
 [-4.  3. -2.  1.]
 [ 8. -7.  6. -5.]]

Original matrix after its third row is multiplied by -2:
[[ 1. -2.  3. -4.]
 [-5.  6. -7.  8.]
 [ 8. -6.  4. -2.]
 [ 8. -7.  6. -5.]]

Original matrix after exchange of the third row with the sum of itself and first row multiplied by 4:
[[  1.  -2.   3.  -4.]
 [ -5.   6.  -7.   8.]
 [  0.  -5.  10. -15.]
 [  8.  -7.   6.  -5.]]

Original matrix after exchange of its first and third rows:
[[-3.  1.  1. -3.]
 [-5.  6. -7.  8.]
 [ 1. -2.  3. -4.]
 [ 8. -7.  6. -5.]]
