In [2]:
# Elimination method to find values.

In [1]:
import numpy as np

In [2]:
a = np.array([[-1, 3], [3,2]], dtype=np.dtype(float))

In [3]:
b = np.array([7,1], dtype=np.dtype(float))

In [4]:
a_system = np.hstack((a, b.reshape((2, 1))))

print(a_system)

[[-1.  3.  7.]
 [ 3.  2.  1.]]


In [5]:
print(a_system[1])

[3. 2. 1.]


In [6]:
a_system_res = a_system.copy()
a_system_res[1] = 3 * a_system_res[0] + a_system_res[1]

print(a_system_res)

a_system_res[1] = 1/11 * a_system_res[1]

print(a_system_res)

[[-1.  3.  7.]
 [ 0. 11. 22.]]
[[-1.  3.  7.]
 [ 0.  1.  2.]]
