In [8]:
import numpy as np

In [1]:
# Elimination method to find values.

In [2]:
a = np.array([[-1, 3], [3,2]], dtype=np.dtype(float))
print(a)

NameError: name 'np' is not defined

In [10]:
b = np.array([7,1], dtype=np.dtype(float))
print(b)

In [11]:
a_system = np.hstack((a, b.reshape((2, 1))))

print(a_system)

[[-1.  3.  7.]
 [ 3.  2.  1.]]


In [12]:
print(a_system[1])

[3. 2. 1.]


In [13]:
a_system_res = a_system.copy()
a_system_res[1] = 3 * a_system_res[0] + a_system_res[1]

print(a_system_res)

a_system_res[1] = 1/11 * a_system_res[1]

print(a_system_res)

[[-1.  3.  7.]
 [ 0. 11. 22.]]
[[-1.  3.  7.]
 [ 0.  1.  2.]]


In [14]:
a_system_res = a_system.copy()
a_system_res[1] = 3 * a_system_res[0] + a_system_res[1]

print(a_system_res)


a_system_res[1] = 1/11 * a_system_res[1]

print(a_system_res)

[[-1.  3.  7.]
 [ 0. 11. 22.]]
[[-1.  3.  7.]
 [ 0.  1.  2.]]
