In [5]:
import numpy as np

In [6]:
A2 = np.array([
        [-1, 3],
        [3, -9]
    ], dtype=np.dtype(float))

b2 = np.array([7, 1], dtype=np.dtype(float))

d2 = np.linalg.det(A2)

print(f"Determinant of matrix A2: {d2:.2f}")

Determinant of matrix A2: 0.00


In [7]:
try:
    x_2 = np.linalg.solve(A2, b2)
except np.linalg.LinAlgError as err:
    print(err)

Singular matrix


In [8]:
A2system = np.hstack((A2, b2.reshape((2, 1))))
print(A2system)

[[-1.  3.  7.]
 [ 3. -9.  1.]]


In [9]:
A2system_res = A2system.copy()

# Multiply row 0 by 3 and add it to the row 1.
A2system_res[1] = 3 * A2system_res[0] + A2system_res[1]
print(A2system_res)

[[-1.  3.  7.]
 [ 0.  0. 22.]]
