In [22]:
import numpy as np

In [23]:
a = np.array([[4,-3,1], [2,1,3], [-1,2,-5]], dtype=np.dtype(float))
b= np.array([-10,0,17], dtype=np.dtype(float))
print("Matrix a:", a)
print("\nMatrix b:", b)
print("\n Shape of a:", np.shape(a))
print("\n Shape of b:", np.shape(b))
solution = np.linalg.solve(a,b)
print("Solution: ", solution)

Matrix a: [[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Matrix b: [-10.   0.  17.]

 Shape of a: (3, 3)

 Shape of b: (3,)
Solution:  [ 1.  4. -2.]


In [24]:
determinant = np.linalg.det(a)
print('Determinant', determinant)

Determinant -60.000000000000036


In [30]:
a_system = np.hstack((a, b.reshape((3, 1))))

In [31]:
print(a_system)

[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


In [33]:
# exchange row_num of the matrix M with its multiple by row_num_multiple
# Note: for simplicity, you can drop check if  row_num_multiple has non-zero value, which makes the operation valid
def MultiplyRow(M, row_num, row_num_multiple):
    # .copy() function is required here to keep the original matrix without any changes
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new

print("Original matrix:")
print(a_system)
print("\nMatrix after its third row is multiplied by 2:")
# remember that indexing in Python starts from 0, thus index 2 will correspond to the third row
print(MultiplyRow(a_system,2,2))

Original matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after its third row is multiplied by 2:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -2.   4. -10.  34.]]


In [34]:
# multiply row_num_1 by row_num_1_multiple and add it to the row_num_2, 
# exchanging row_num_2 of the matrix M in the result
def AddRows(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] = row_num_1_multiple * M_new[row_num_1] + M_new[row_num_2]
    return M_new

print("Original matrix:")
print(a_system)
print("\nMatrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:")
print(AddRows(a_system,1,2,1/2))

Original matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:
[[  4.   -3.    1.  -10. ]
 [  2.    1.    3.    0. ]
 [  0.    2.5  -3.5  17. ]]


In [35]:
# exchange row_num_1 and row_num_2 of the matrix M
def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

print("Original matrix:")
print(a_system)
print("\nMatrix after exchange its first and third rows:")
print(SwapRows(a_system,0,2))

Original matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after exchange its first and third rows:
[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


In [44]:
A_ref = SwapRows(a_system,0,2)
A_ref = AddRows(A_ref,0,1,2)
A_ref = AddRows(A_ref,0,2,4)
A_ref = AddRows(A_ref,1,2,-1)
A_ref = MultiplyRow(A_ref,2,-1/12)
print(A_ref)


[[-1.  2. -5. 17.]
 [ 0.  5. -7. 34.]
 [-0. -0.  1. -2.]]


In [45]:
x_3 = -2
x_2 = (A_ref[1,3] - A_ref[1,2] * x_3) / A_ref[1,1]
x_1 = (A_ref[0,3] - A_ref[0,2] * x_3 - A_ref[0,1] * x_2) / A_ref[0,0]

print(x_1, x_2, x_3)

1.0 4.0 -2
