In [4]:
#Chapter 1 week 1
# to make an 1d array
import numpy as np
age = np.array([20,23,45])
age_np_arange = np.arange(1,20,3) # begins with 1, ends with 20, incremented by 3

In [5]:
print(age.dtype)

int64


In [8]:
vector_a = np.array([[5],[7]])
print(vector_a)
print(vector_a.dtype)
print(vector_a.shape)

[[5]
 [7]]
int64
(2, 1)


In [14]:
one_d_array = np.array([20,25,40])
print(one_d_array.shape)
print(one_d_array.size)
print(one_d_array.ndim)

(3,)
3
1


In [17]:
reshape_one_d_to_two_d_array = np.reshape(one_d_array, (3,1))
print(reshape_one_d_to_two_d_array)
print(reshape_one_d_to_two_d_array.shape)
print(reshape_one_d_to_two_d_array.size)
print(reshape_one_d_to_two_d_array.ndim)

[[20]
 [25]
 [40]]
(3, 1)
3
2


In [16]:
height = np.array([280,450,360,450])
print(height.shape)
print(height.size)
print(height.ndim)

(4,)
4
1


In [20]:
two_d_array = np.array([[12,24,36],[13,26,39]])
print(two_d_array)
print(two_d_array.shape)
print(two_d_array.size)
print(two_d_array.ndim)

[[12 24 36]
 [13 26 39]]
(2, 3)
6
2


In [24]:
# to find solution of linear equation  for eq 1: 3u+z = 15 & u+2z =10 
coeff_a = np.array([[3,1],[1,2]], dtype=np.dtype(float))
b = np.array([15,10], dtype=np.dtype(float))
print(coeff_a.shape, b.shape)
print("Matrix A:", coeff_a)
print("Matrix B:", b)
# to find x
X = np.linalg.solve(coeff_a,b)
print("The solutions are: ", X)

(2, 2) (2,)
Matrix A: [[3. 1.]
 [1. 2.]]
Matrix B: [15. 10.]
The solutions are:  [4. 3.]


In [ ]:
matrix_b = np.array([[1,2,3],[2,4,6],[3,4,5]])
