In [1]:
import pandas as pd
import numpy as np

In [2]:
path = "data/house_prices_train.csv"
data_frames = pd.read_csv(path)
print("Head gives top 5 information with 5 rows * total cols",data_frames.head())
print("About column information", data_frames.columns)
print("To count total data", data_frames.count)

Head gives top 5 information with 5 rows * total cols    Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  Sale

In [3]:
X_multi = data_frames[['GrLivArea', 'OverallQual']] # Selected two features from the csv
Y_multi = data_frames['SalePrice'] # Output for the given data

print(X_multi, Y_multi)

      GrLivArea  OverallQual
0          1710            7
1          1262            6
2          1786            7
3          1717            7
4          2198            8
...         ...          ...
1455       1647            6
1456       2073            6
1457       2340            7
1458       1078            5
1459       1256            5

[1460 rows x 2 columns] 0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64


In [4]:
# display function is jupyter notebook function allowing to display in neat way
display(X_multi)
display(Y_multi)

GrLivArea  OverallQual
0          1710            7
1          1262            6
2          1786            7
3          1717            7
4          2198            8
...         ...          ...
1455       1647            6
1456       2073            6
1457       2340            7
1458       1078            5
1459       1256            5

[1460 rows x 2 columns]

0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [5]:
# Normalizing data using x - mean / std deviation, to make ranges common or similar to each other.
X_multi_normalize = (X_multi - np.mean(X_multi))/np.std(X_multi)
Y_multi_normalize = (Y_multi - np.mean(Y_multi))/np.std(Y_multi)
print(X_multi_normalize)
print(Y_multi_normalize)

      GrLivArea  OverallQual
0      1.807001  -545.221740
1      0.954156  -545.945056
2      1.951680  -545.221740
3      1.820327  -545.221740
4      2.735994  -544.498425
...         ...          ...
1455   1.687070  -545.945056
1456   2.498034  -545.945056
1457   3.006315  -545.221740
1458   0.603880  -546.668371
1459   0.942734  -546.668371

[1460 rows x 2 columns]
0       0.347273
1       0.007288
2       0.536154
3      -0.515281
4       0.869843
          ...   
1455   -0.074560
1456    0.366161
1457    1.077611
1458   -0.488523
1459   -0.420841
Name: SalePrice, Length: 1460, dtype: float64


In [6]:
# Transposing shape, since at a time in a neuron only two features of first rows is an input hence, reshaping.
print(X_multi_normalize.shape, Y_multi_normalize)
X_multi_normalize = np.array(X_multi_normalize).T
Y_multi_normalize = np.array(Y_multi_normalize).reshape((1,len(Y_multi_normalize)))
print(X_multi_normalize.shape,Y_multi_normalize.shape)                                                    

(1460, 2) 0       0.347273
1       0.007288
2       0.536154
3      -0.515281
4       0.869843
          ...   
1455   -0.074560
1456    0.366161
1457    1.077611
1458   -0.488523
1459   -0.420841
Name: SalePrice, Length: 1460, dtype: float64
(2, 1460) (1, 1460)


In [7]:
def layer_sizes(X,Y):
    # Getting number of features = 2, to feed in one network and for output its the price, i.e 1 output
    n_x = X.shape[0]
    n_y = Y.shape[0]
    return (n_x,n_y)

(n_x,n_y) = layer_sizes(X_multi_normalize, Y_multi_normalize)
print("The size of input layer", n_x)
print("The size of output layer", n_y)

The size of input layer 2
The size of output layer 1


In [8]:
def initialize_parameters(n_x, n_y):
    W = np.random.randn(n_y,n_x) * 0.01
    b = np.zeros((n_y,1))
    parameters= {"W":W, "b":b}
    return parameters

parameters = initialize_parameters(n_x, n_y)
print(parameters)

{'W': array([[ 0.01245473, -0.00514406]]), 'b': array([[0.]])}


In [9]:
def forward_propagation(X, parameters):
    W = parameters["W"]
    b = parameters["b"]
    # y = wx + b
    predicted_y = np.matmul(W, X) + b
    return predicted_y

y_hat = forward_propagation(X_multi_normalize, parameters)
print(y_hat[0, 0:5]) # first five predicted price
    

[2.82715789 2.82025671 2.82895983 2.82732386 2.83500746]


In [10]:
def compute_cost(actual_y, predicted_y):
    total_number_outputs_y = predicted_y.shape[1]
    try:
        # print(actual_y, predicted_y)
        # Fix this overflow error issue in finding cost
        # squared_error = np.square(actual_y - predicted_y)
        squared_error = actual_y - predicted_y
        # print(squared_error,"Square")
        mean_squared_error = np.sum(squared_error)/(2*total_number_outputs_y)
        #print(mean_squared_error)
        return(mean_squared_error)
    except RuntimeWarning as e:
        print(e)
            
    

print("The cost function value is:",compute_cost(Y_multi_normalize,y_hat))
    

The cost function value is: -1.4129483679455568


In [11]:
def backward_propagation(predicted_y,actual_y, X):
    #print(X.shape[1], X.shape)
    input_size_m = X.shape[1]
    difference_in_output = predicted_y - actual_y
    #print(difference_in_output.shape)
    gradient_of_b = 1/input_size_m * (np.sum(difference_in_output*X))
    gradient_of_w = 1/input_size_m * np.dot(difference_in_output,X.T)
    gradients = {"dW": gradient_of_w, "db" : gradient_of_b}
    return gradients
    
gradients = backward_propagation(y_hat, Y_multi_normalize, X_multi_normalize)
print(gradients)

{'dW': array([[    3.3606548 , -1543.37008891]]), 'db': -1540.0094341050785}


In [12]:
def each_level_grad_descent_for_parameters_update(gradients_w_b, parameters_w_b, learning_rate= 1.2):
    W = parameters_w_b["W"]
    b = parameters_w_b["b"]
    
    dW = gradients_w_b["dW"]
    db = gradients_w_b["db"]
    
    W = W - learning_rate * dW
    b = b - learning_rate * db
    parameters = {"W": W, "b":b}
    return parameters

print("The updated parameters from backward propagation",each_level_grad_descent_for_parameters_update(gradients,parameters))

The updated parameters from backward propagation {'W': array([[  -4.02033103, 1852.03896263]]), 'b': array([[1848.01132093]])}


In [49]:
def nn_model(input_X,output_label_Y, iterations = 10, learning_rate = 1.2, print_cost= False):
    # Training model by feeding training data and testing for new data
    nn_layer_size = layer_sizes(input_X, output_label_Y)
    nn_input_feature_layer = nn_layer_size[0]
    nn_output_price_layer = nn_layer_size[1]
    parameters = initialize_parameters(nn_input_feature_layer, nn_output_price_layer)
    print(parameters,"BEGIN")
    
    for i in range(0,iterations):
        y_hat = forward_propagation(input_X, parameters)
        cost = compute_cost(output_label_Y,y_hat)
        gradients = backward_propagation(y_hat, output_label_Y, input_X)
        # parameters = each_level_grad_descent_for_parameters_update(gradients, parameters)
        #print("Update parameters", parameters)
        if(print_cost):
            print("Cost is %f", cost)
    return parameters

print("Neural Network", nn_model(X_multi_normalize, Y_multi_normalize, 100, 1.2))
    

{'W': array([[-0.00847518,  0.00131117]]), 'b': array([[0.]])} BEGIN
Neural Network {'W': array([[-0.00847518,  0.00131117]]), 'b': array([[0.]])}


In [51]:
def predict(X_data,Y_data,updated_parameters,X_test):
    print(X_data,Y_data, updated_parameters)
    W = updated_parameters["W"]
    b = updated_parameters["b"]
    print(isinstance(X_data,pd.Series), pd.Series, X_data.shape, X_test.shape)
    
    if isinstance(X_data,pd.Series):
        X_mean = np.mean(X_data)
        X_deviation = np.std(X_data)
        x_normalized = ((X_test - X_mean)/X_std).reshape((1, len(X_test)))
    else:
        # X_mean = np.array(np.mean(X_data)).reshape((len(X_data.axes[1]),1))
        X_mean = np.array(np.mean(X_data))
        X_std = np.array(np.std(X_data)).reshape((len(X_data.axes[1]),1))
        x_normalized = ((X_test - X_mean)/X_std)
    y_pred_normalize = np.matmul(W,x_normalized) + b
    y_pred = y_pred_normalize * np.mean(Y_data) + np.std(Y_data)
    return y_pred[0]
    
    
    

In [42]:
parameters_multi = nn_model(X_multi_normalize, Y_multi_normalize, iterations=100, print_cost=False)

{'W': array([[ 0.00103806, -0.00717155]]), 'b': array([[0.]])} BEGIN


In [43]:
print("W is", parameters_multi["W"])
print("b is", parameters_multi["b"])
multi_params_w = parameters_multi["W"]
multi_params_b = parameters_multi["b"]

W is [[ 0.00103806 -0.00717155]]
b is [[0.]]


In [53]:
X_test_data =  np.array([[1710, 7], [1200, 6], [2200, 8]])
X_test_data_formatted =  np.array([[1710, 7], [1200, 6], [2200, 8]]).T
print("Before transpose",X_test_data.shape)
print("After transpose",X_test_data_formatted.shape)
Y_test_data_output = predict(X_multi, Y_multi, parameters_multi, X_test_data_formatted)

print(f"Ground living area, square feet:\n{X_test_data_formatted[0]}")
print(f"Rates of the overall quality of material and finish, 1-10:\n{X_test_data_formatted[1]}")
print(f"Predictions of sales price, $:\n{np.round(Y_test_data_output)}")


Before transpose (3, 2)
After transpose (2, 3)
      GrLivArea  OverallQual
0          1710            7
1          1262            6
2          1786            7
3          1717            7
4          2198            8
...         ...          ...
1455       1647            6
1456       2073            6
1457       2340            7
1458       1078            5
1459       1256            5

[1460 rows x 2 columns] 0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64 {'W': array([[ 0.00103806, -0.00717155]]), 'b': array([[0.]])}
False <class 'pandas.core.series.Series'> (1460, 2) (2, 3)
Ground living area, square feet:
[1710 1200 2200]
Rates of the overall quality of material and finish, 1-10:
[7 6 8]
Predictions of sales price, $:
[787172. 787928. 786408.]
