In [1]:
# Creating 1-D array
# Use shift+ tab for documentation
import numpy as np

a = np.array([12,14])
print(a.shape) # 1D array 
reshape_a = np.reshape(a,(2,-1))
print(reshape_a.shape)

(2,)
(2, 1)


In [2]:
array_1 = np.arange(0,20,2) # Start = 0 , end = 20, space of 2, included 0
print(array_1)
array_2 = np.linspace(0,20,6) # Start from 0,include 20 end with 20 where output has 4 elements.Last value represent how many elements in an array you want.
print(array_2)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0.  4.  8. 12. 16. 20.]


In [3]:
zeros_arr = np.zeros((2,3)) # 2 rows, 3 columns filled with 0's , defined, intialized every element to be 0
ones_arr = np.ones((1,3))
empty_arr = np.empty(3) # defined there's an empty array but uninitalized.
random = np.random.randn(4)
print(zeros_arr,ones_arr,empty_arr, random)

[[0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]] [3. 2. 1.] [-0.26619091 -1.06792966  0.60498914  0.14546578]


In [4]:
#DIMENSION: length, width, height of an array, returns integer value
oneD_a = np.array([10,20,30])
twoD_a = np.array([[10,23,56],[3,4,5]])
reshaped_twoD_a = twoD_a.reshape((3,2,1))
threeD_a = np.array([[[10,12],[12,14]],[[14,15],[16,20]]])
print(oneD_a.ndim, twoD_a.ndim)
print(reshaped_twoD_a.ndim)
print(threeD_a.ndim,threeD_a[0][0])

1 2
3
3 [10 12]


In [5]:
# SHAPE: length of each dimension,returns tuple: tuple in python is similar to list,but in tuple wrapped with (),and is immutable, ordered.
tuple_a = ('anjila', 25)
print(tuple_a, tuple_a[0], tuple_a[1])
# Immutability
# tuple_a[2] = 100
oneD_a = np.array([10,20,30])
twoD_a = np.array([[10,23,56],[3,4,5]])
reshaped_twoD_a = twoD_a.reshape((3,2,1))
threeD_a = np.array([[[10,12],[12,14]],[[14,15],[16,20]]])
print('one d shape',oneD_a.shape, 'Two d shape',twoD_a.shape)
print(reshaped_twoD_a.shape)
print("Shape of 3d array",threeD_a.shape)

('anjila', 25) anjila 25
one d shape (3,) Two d shape (2, 3)
(3, 2, 1)
Shape of 3d array (2, 2, 2)


In [6]:
# SIZE: total number of elements in an array.
oneD_a = np.array([10,20,30])
twoD_a = np.array([[10,23,56],[3,4,5]])
reshaped_twoD_a = twoD_a.reshape((3,2,1))
threeD_a = np.array([[[10,12],[12,14]],[[14,15],[16,20]]])
print(oneD_a.size,'Size')
print(twoD_a.size,'Size')
print(threeD_a.size,'Size')

3 Size
6 Size
8 Size


BROADCASTING: Numpy can perform mathematical operations in an array of different shapes. For example: 
Below we observe that a.shape is (2,) is 1d ARRAY, and when scalar is multiplied, scalar is also converted into (2,) such that 
each element in array is multiplied by scalar.

In [7]:
a_test = np.array([10,20])
scalar_val = 2
# Here you can multiply scalar to array
print(a_test * scalar_val)

[20 40]


In [ ]:
# Just test